//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.BILLs = new HashSet<BILL>();
        }
    
        public string eID { get; set; }
        public string eName { get; set; }
        public Nullable<System.DateTime> eDOB { get; set; }
        public string ePhoneNum { get; set; }
        public string eIDCardNum { get; set; }
        public Nullable<int> eBaseSalary { get; set; }
        public Nullable<int> eKPI { get; set; }
        public Nullable<System.DateTime> eStartDay { get; set; }
        public Nullable<int> eGrossSalary { get; set; }
        public string ePosition { get; set; }
        public string ePassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILLs { get; set; }
    }
}
