//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Bill_Product_Detail = new HashSet<Bill_Product_Detail>();
        }
    
        public string pID { get; set; }
        public string pName { get; set; }
        public string pBrand { get; set; }
        public string pDescription { get; set; }
        public Nullable<int> pWarranty_time { get; set; }
        public Nullable<int> pQuantity { get; set; }
        public Nullable<int> pPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_Product_Detail> Bill_Product_Detail { get; set; }
    }
}
